apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
  template: 
    spec:
      containers:
        - name: app-b
          image: pranavpracto/sample-service-a:0.0.1-SNAPSHOT
          ports:
            - containerPort: 9090

